### ISSUE TITLE
Missing yargs

### ISSUE THREAD

**Issue by xverges** [kba/hocrjs#23]
```
$ hocrjs-inject blahblah

module.js:471
    throw err;
    ^

Error: Cannot find module 'yargs'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/hocrjs/bin/hocrjs-inject.js:11:30)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```
Looks like `yargs` is set as a devdependency, not as a run-time dependency

**Comment by Ortega-Dan** [comment]
You are right, I installed yargs and it solved the issue.
npm install -g yargs
